= Coding Exercise - Message Queue

A charge point needs to notify a backend system when a charging session starts and ends. 

A `StartTransaction`-Message contains the following attributes:

* `connector_id`: an integer that stores the id of the connector that is used for the charging session. Value must be greater than 0.
* `id_tag`: a string that stores the id of the user that starts the charging session.
* `meter_start`: a float that stores the meter value at the start of the charging session.
* `timestamp`: a string that stores the time at which the charging session starts.

A `StopTransaction`-Message contains the following attributes:

* `connector_id`: an integer that stores the id of the connector that is used for the charging session.
* `transaction_id`: an integer that stores the id of the transaction that is ended.
* `meter_stop`: a float that stores the meter value at the end of the charging session.
* `timestamp`: a string that stores the time at which the charging session ends.

Take into account that further messages could be added easily in the future.
All messages contain a `timestamp`.

Those messages need to be added to a queue. Create a `LoggingMessageQueue` class with the following
attributes and methods:

* `add_message`: a method that adds a new message to the queue.
* `get_message`: a method that removes and returns the message at the front of the queue.
If the queue is empty, it should return `None`.

The `LoggingMessageQueue` logs the message type and its timestamp when a message is added and removed from the queue. Standard print statements are sufficient for this purpose.
Consider that there might be other implementations of the concept `MessageQueue` in the future.
Make sure that the `MessageQueue` class can be easily replaced by another implementation
without modifying the code that uses it.

