= DevOps Exercise

Checking the following skills:

* Scripting
* Linux
* Raspberry Pi

Create a minimal service for the monitoring of operational system parameters:

* CPU temperature
* CPU usage
* RAM usage
* disk usage 

(choose two)

The service should continuously write into a machine-readable CSV file in a fixed file system location.

The service should run automatically at boot and keep logs written during previous boots.

The service deployment should be automated. This means one can run e.g.

    ./setup_service

to (re-)install the service on the device.
All files and scripts needed for this purpose should be available in one directory.


== Device (Remote)

Hostname: `ssh.interview.hostedpi.com`
Port: `5115`
User: `root`

Send us a public SSH key. It needs to be authorized on the server.

You can test the login using

    ssh -p 5115 root@ssh.interview.hostedpi.com uname -a


== Device (Local)

Network: `WasGehtLan`
Hostname: `raspberrypi-interview`
IP: `192.168.178.127`
MAC: `B8:27:EB:3C:FB:E5`
User: `pi`
Password: `raspberry`

The public key of the `noadmin` user is authorized to login on the `pi` user without password.

You can test the login using

    ssh pi@raspberrypi-interview uname -a

